buildConfig: ./behavior-config.yml
behavior: ./behaviors/soundcloud/artist.js
url: 'https://soundcloud.com/kot_68/tracks'

# path to chrome executable or command
# chromeEXE: google-chrome-unstable
openDevTools: true

mode: build-watch
# available options:
#  - build-watch: build and run the behavior watching for changes
#  - build: build and run the behavior once
#  - built: just run the previously built behavior

# time values in seconds
#timeout: 60
#slowmo: 10
