FROM node:11.11.0

ENV DOCKER 1

WORKDIR /app

COPY behaviors /app/behaviors
COPY internal /app/internal
COPY lib /app/lib
COPY package.json behavior-config.yml tsconfig.json /app/

RUN yarn install

VOLUME /dist

CMD ["yarn", "run", "build-behaviors"]
